FROM ubuntu:16.04

# Set the working directory to /app
WORKDIR /app

# Update package list and install necessary packages using apt-get
RUN apt-get update && apt-get install -y \
  arp-scan \
  iputils-ping \
  iproute2

# Copy the web application to the container
COPY . .

# Set the default command to execute when the container starts
CMD ["/bin/bash"]
